title: Development the way it should be
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and learnings from an agile developer. Mostly a
  self-learning journey, hopefully helping other people along the
  way.
disqus_shortname: jlordiales
reading_time:     false
  
#Your site's domain goes here. Leave localhost server or blank when working locally.
url: "http://jlordiales.me" # the base hostname & protocol for your site
#url: "http://localhost:4000"

# Owner/author information
owner:
  name:           Jose Luis Ordiales
  avatar:         avatar.jpg
  bio:            "Professional software developer and scientist. Naturally curious and critical thinker"
  email:          jlordiales@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  github:         jlordiales
  linkedin:       jordiales
  twitter:        jlordiales
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +JoseLuisOrdialesCoscia

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-56085926-1

# Links to include in top navigation
# For external links add external: true
links:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks

permalink: /:year/:month/:day/:title

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["vendor","lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
